name: CI/CD - OpeMay Backend (Node + Docker + AWS EC2)

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: canarvaezis/seminario_asiaticas_opemay_backend:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Desplegando nueva versión en EC2..."

            docker pull canarvaezis/seminario_asiaticas_opemay_backend:latest

            docker stop seminario_backend || true
            docker rm seminario_backend || true

            docker image prune -f

            docker run -d \
              --name seminario_backend \
              --restart always \
              -e NODE_ENV=production \
              -e PORT=43263 \
              -e VERSION=1.49.2 \
              -e CORS_ORIGIN=* \
              -e FIREBASE_KEY_PATH=/app/firebase-key.json \
              -v /home/ec2-user/secrets/firebase-key.json:/app/firebase-key.json \
              -p 43263:43263 \
              canarvaezis/seminario_asiaticas_opemay_backend:latest